// See verilog_out.h.

#include "engines/netlistgen/verilog_out.h"

#include <fstream>
#include <string>
#include <vector>

#include "odb/db.h"
#include "support/logging.h"
#include "utl/Logger.h"

namespace eda {

namespace {

constexpr const char* kGroup = "netlistgen";

// The Verilog identifier a net is referred to by. A net that terminates a
// primary port carries a dbBTerm whose name (pi<i>/po<i>) IS the port name
// declared in the module header; an instance pin on that same net must use the
// SAME identifier to stay electrically connected in Verilog (where a top-level
// port is itself a wire). So a port net is named by its bTerm, every other net
// by its own dbNet name.
//
// This is the one deliberate deviation from the brief's literal
// "net_name = dbITerm::getNet()::getName()": following that verbatim would make
// a combinational PI's port (pi0) and the instance pins it feeds (net "n123")
// two disconnected signals. Since Stage E1 gives each net at most one bTerm
// (PI nets are fresh with one INPUT bterm; PO reuses/creates a net with one
// OUTPUT bterm), taking the first bTerm's name is unambiguous. Non-port nets
// are unaffected, so the wire-name vs DEF-net-name consistency guarantee holds
// exactly for every wire actually emitted.
std::string verilogNetName(odb::dbNet* net)
{
  odb::dbSet<odb::dbBTerm> bterms = net->getBTerms();
  if (!bterms.empty()) {
    return std::string((*bterms.begin())->getName());
  }
  return std::string(net->getName());
}

}  // namespace

bool writeVerilog(odb::dbBlock* block,
                  const std::string& path,
                  const std::string& top_module_name,
                  utl::Logger* logger)
{
  if (block == nullptr) {
    return false;
  }

  std::ofstream out(path);
  if (!out) {
    return false;
  }

  // ---- Module header + port list ----
  // Ports are the block's dbBTerms, inputs first then outputs, each group in
  // dbBlock::getBTerms() iteration order (creation/db order). Split once so the
  // header list, the input decls, and the output decls all agree.
  std::vector<odb::dbBTerm*> inputs;
  std::vector<odb::dbBTerm*> outputs;
  for (odb::dbBTerm* bterm : block->getBTerms()) {
    if (bterm->getIoType() == odb::dbIoType::INPUT) {
      inputs.push_back(bterm);
    } else {
      outputs.push_back(bterm);  // OUTPUT/INOUT treated as an output port
    }
  }

  out << "// Generated by eda-lab netlistgen (structural Verilog, Stage E2).\n";
  out << "// Instance and net names match the .def / .odb written from the "
         "same block.\n";
  out << "module " << top_module_name << " (";
  {
    bool first = true;
    const auto emitPort = [&](odb::dbBTerm* bterm) {
      out << (first ? "\n    " : ",\n    ") << bterm->getName();
      first = false;
    };
    for (odb::dbBTerm* bterm : inputs) {
      emitPort(bterm);
    }
    for (odb::dbBTerm* bterm : outputs) {
      emitPort(bterm);
    }
    out << (first ? ");\n" : "\n);\n");  // empty list -> "module top ();"
  }

  for (odb::dbBTerm* bterm : inputs) {
    out << "    input  " << bterm->getName() << ";\n";
  }
  for (odb::dbBTerm* bterm : outputs) {
    out << "    output " << bterm->getName() << ";\n";
  }
  out << "\n";

  // ---- Wire declarations ----
  // One per dbNet, EXCEPT nets that terminate a primary port: those are already
  // declared as input/output and are referred to by the port (bTerm) name, so a
  // second `wire` decl would redeclare the identifier.
  for (odb::dbNet* net : block->getNets()) {
    if (!net->getBTerms().empty()) {
      continue;
    }
    out << "    wire " << net->getName() << ";\n";
  }
  out << "\n";

  // ---- Instances ----
  // Cell type = master name; instance name = dbInst name; one .port(net)
  // connection per CONNECTED iterm (unconnected pins are skipped). Boundary
  // buffer/FF cells inserted by Stage E1 are ordinary instances here — no
  // special casing (they are distinguished only by planes, never by name).
  for (odb::dbInst* inst : block->getInsts()) {
    out << "    " << inst->getMaster()->getName() << " " << inst->getName()
        << " (";
    bool first = true;
    for (odb::dbITerm* iterm : inst->getITerms()) {
      odb::dbNet* net = iterm->getNet();
      if (net == nullptr) {
        continue;  // unconnected pin
      }
      out << (first ? "\n        ." : ",\n        .")
          << iterm->getMTerm()->getName() << "(" << verilogNetName(net) << ")";
      first = false;
    }
    out << (first ? ");\n" : "\n    );\n");
  }

  out << "\nendmodule\n";

  out.flush();
  const bool good = out.good();
  out.close();
  if (!good) {
    return false;
  }
  if (logger != nullptr) {
    debugPrint(logger, utl::UKN, kGroup, kVerbosityDetail,
               "Wrote structural Verilog: {} ({} ports, {} nets, {} insts)",
               path, block->getBTerms().size(), block->getNets().size(),
               block->getInsts().size());
  }
  return true;
}

}  // namespace eda
